Step4/Controllers/MainController.cs
using MessagePostingApp.Services;
 using Microsoft.AspNetCore.Mvc;

namespace MessagePostingApp.Controllers {
    
    [ApiController]
    [Route("api")]
    public class MainController : ControllerBase {
        private readonly MessagesService messagesService;

        public MainController(MessagesService messagesService) {
            this.messagesService = messagesService;
        }

        [HttpGet("json-msg")]
        //GET /api/json-msg
        public IActionResult GetJsonMessages() {
            return new JsonResult(messagesService.GetMessages());
        }
    }
}

Step4/Pages/Admin.cshtml.cs
using MessagePostingApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MessagePostingApp.Pages {
    public class AdminModel : PageModel {

        private readonly MessagesService messagesService;

        public AdminModel(MessagesService messagesService) {
            this.messagesService = messagesService;
        }
        
        public IActionResult OnGet() {
            return Page();
        }

        public IActionResult OnPostCleanMessages() {
            messagesService.CleanMessages();
            return Page();
        }
    }
}

Step4/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MessagePostingApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Step4/Pages/Index.cshtml.cs
﻿using System.ComponentModel.DataAnnotations;
 using MessagePostingApp.Model;
 using MessagePostingApp.Services;
 using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MessagePostingApp.Pages {
    public class IndexModel : PageModel {

        private readonly MessagesService messagesService;
        
        [BindProperty]
        [Required(ErrorMessage = "Name is required")]
        [StringLength(16, MinimumLength = 3)]
        public string Name { get; set; }
        
        [BindProperty]
        [Required(ErrorMessage = "Message is required")]
        [StringLength(16, MinimumLength = 3)]
        public string Message { get; set; }

        public IndexModel(MessagesService _messagesService) {
            this.messagesService = _messagesService;
        }
        
        public IActionResult OnGet() {
            return Page();
        }

        public IActionResult OnPost() {
            if (!ModelState.IsValid) {
                return Page();
            }

            var msg = new Message {
                Name = Name,
                Msg = Message
            };
            
            messagesService.AddMessage(msg);
            
            return Page();
        }
    }
}

Step4/Pages/Admin.cshtml
﻿@page
@model AdminModel
@{
    ViewData["Title"] = "John Deere Day";
}

<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
            <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
        </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <h1>John Deere Day - ITS - Admin Control Panel</h1>
        <form method="post">
            <br>
            <button type="submit" asp-page-handler="CleanMessages" class="btn btn-primary">CleanMessages</button><br><br>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

Step4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "John Deere Day";
}
@section Scripts {
    <script src="js/index.js"></script>
}
@section Styles {
    <link rel="stylesheet" href="css/index.css"/>
}


<div class="row">
    <div class="col-lg-6 text-center">
        <img src="images/JDLogo.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
    
    <div class="col-lg-6 text-center">
        <img src="images/ITS.png" width="300px" class="img-fluid" alt="Responsive image">
    </div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <h1>John Deere Day - ITS</h1>
        <form method="post">
            <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" class="form-control" id="Name" name="Name" aria-describedby="emailHelp" placeholder="Your name">
                <small class="form-text text-muted">16 characters max. No Special Characters</small>
            </div>
            <div class="form-group">
                <label for="Message">A message</label>
                <input type="text" name="Message" class="form-control" id="Message" placeholder="A messgage">
                <small class="form-text text-muted">16 characters max. No Special Characters</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button><br>
            <small class="form-text text-muted">The message will be automatically deleted after 30sec or when reaching 50.</small>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6 text-center">
        <div id="divMessages">
            
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>

Step4/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MessagePostingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Message Posting App - JD - ITS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MessagePostingApp
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>